name: Build a JAR in spring boot using springboot
on:
  push:
    branches:
      - main



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3



      - name: Set up JDK 11
        uses: actions/setup-java@v3



        with:
          java-version: '21'



      - name: Build with Maven
        run: mvn clean install



      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2



        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'



      - name: Run Tests
        run: mvn test

